name: CD

# on:
#   release:
#     types: [published]
on:
  pull_request:
  push:

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Authenticate npm
        run: |
          npm config set @nersent:registry https://npm.pkg.github.com
          npm config set -- '//npm.pkg.github.com:_authToken' "${{ secrets.NPM_TOKEN }}"

      - name: Bump version
        uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          version: "1.0.0"

      - uses: actions/cache@v3.0.2
        id: yarn-cache
        with:
          path: |
            node_modules
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile
        env:
          ADBLOCK: true

      - name: Publish
        run: |
          cat package.json

          npm publish --dry-run
        # readonly VERSION_TAG=1.2.0

        # npm version $VERSION_TAG

# $(git describe --abbrev=7 --tags HEAD)
